compatibility_date = "2021-09-26"
name = "status"
workers_dev = true
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "./out"
entry-point = "./"
