compatibility_date = "2021-09-26"
name = "status"
workers_dev = true
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
kv_namespaces = [{ binding = "KV_STATUS_PAGE", id = "76a90da7391740ab9dbb35849acd61f6" }]

[triggers]
crons = ["* * * * *"]

[site]
bucket = "./out"
entry-point = "./"
